imports:
    - { resource: "@Tavy315SyliusRecommendationsPlugin/Resources/config/app/grids.yaml" }
    - { resource: "@Tavy315SyliusRecommendationsPlugin/Resources/config/app/jms_serializer.yaml" }

services:
    tavy315_sylius_recommendations.context.customer_recommendation:
        class: Tavy315\SyliusRecommendationsPlugin\Context\CustomerRecommendationContext
        public: true
        arguments:
            - "@tavy315_sylius_recommendations.factory.customer_recommendation"
            - "@tavy315_sylius_recommendations.repository.customer_recommendation"
            - "@sylius.context.locale"
            - "@tavy315_sylius_recommendations.repository.recommendation_group"
            - "@security.token_storage"

    tavy315_sylius_recommendations.controller.action.list_recommendation_groups:
        class: Tavy315\SyliusRecommendationsPlugin\Controller\Action\ListRecommendationGroupsAction
        arguments:
            - "@tavy315_sylius_recommendations.context.customer_recommendation"
            - "@twig"
        tags:
            - { name: controller.service_arguments }

    tavy315_sylius_recommendations.controller.action.list_recommendation_products:
        class: Tavy315\SyliusRecommendationsPlugin\Controller\Action\ListRecommendationProductsAction
        arguments:
            - "@tavy315_sylius_recommendations.context.customer_recommendation"
            - "@tavy315_sylius_recommendations.repository.product"
            - "@twig"
            - "@tavy315_sylius_recommendations.request_data_handler.pagination"
            - "@sylius.context.shopper"
        tags:
            - { name: controller.service_arguments }

    tavy315_sylius_recommendations.controller.recommendation_group_slug:
        class: Tavy315\SyliusRecommendationsPlugin\Controller\RecommendationGroupSlugController
        arguments:
            - "@sylius.generator.slug"
        tags:
            - { name: controller.service_arguments }

    tavy315_sylius_recommendations.custom_factory.customer_recommendation:
        class: Tavy315\SyliusRecommendationsPlugin\Factory\CustomerRecommendationFactory
        decorates: tavy315_sylius_recommendations.factory.customer_recommendation
        public: false
        arguments:
            - "@tavy315_sylius_recommendations.custom_factory.customer_recommendation.inner"

    tavy315_sylius_recommendations.request_data_handler.pagination:
        class: Tavy315\SyliusRecommendationsPlugin\RequestDataHandler\PaginationDataHandler

sylius_ui:
    events:
        tavy315_sylius_recommendations.admin.recommendation_group.create.javascripts:
            blocks:
                recommendation_group:
                    template: '@Tavy315SyliusRecommendationsPlugin/Admin/RecommendationGroup/_javascripts.html.twig'
                    context:
                        postfix: create.javascripts
        tavy315_sylius_recommendations.admin.recommendation_group.update.javascripts:
            blocks:
                recommendation_group:
                    template: '@Tavy315SyliusRecommendationsPlugin/Admin/RecommendationGroup/_javascripts.html.twig'
                    context:
                        postfix: update.javascripts
