sylius_grid:
    templates:
        action:
            tavy315_sylius_recommendations_default: "@Tavy315SyliusRecommendationsPlugin/Admin/Grid/Action/tavy315_sylius_recommendations_default.html.twig"

    grids:
        sylius_admin_customer:
            actions:
                item:
                    show_recommendations:
                        label: tavy315_sylius_recommendations.ui.show_recommendations
                        options:
                            link:
                                parameters:
                                    id: resource.id
                                route: tavy315_sylius_recommendations_admin_customer_customer_recommendation
                        position: 0
                        type: show

        tavy315_sylius_recommendations_admin_customer_recommendation:
            driver:
                options:
                    class: "%tavy315_sylius_recommendations.model.customer_recommendation.class%"
            fields:
                customer:
                    type: twig
                    label: sylius.ui.customer
                    sortable: customer.lastName
                    options:
                        template: "@SyliusAdmin/Order/Grid/Field/customer.html.twig"
                recommendationGroup:
                    type: string
                    label: tavy315_sylius_recommendations.ui.recommendation_group
            sorting:
                recommendationGroup: asc
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update

        tavy315_sylius_recommendations_admin_customer_customer_recommendation:
            extends: tavy315_sylius_recommendations_admin_customer_recommendation
            driver:
                options:
                    repository:
                        method: findGroupsByCustomerId
                        arguments:
                            customerId: $id
            fields:
                customer:
                    enabled: false
                    type: string

        tavy315_sylius_recommendations_admin_recommendation_group:
            driver:
                options:
                    class: "%tavy315_sylius_recommendations.model.recommendation_group.class%"
            fields:
                code:
                    type: string
                    label: sylius.ui.code
                    sortable: ~
                name:
                    type: string
                    label: tavy315_sylius_recommendations.ui.name
                    sortable: ~
            filters:
                name:
                    type: string
                    label: tavy315_sylius_recommendations.ui.name
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
