Tavy315\SyliusRecommendationsPlugin\Entity\RecommendationGroup:
    exclusion_policy: ALL
    xml_root_name: recommendation_group
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
            groups: [Default, Detailed, Autocomplete]
        code:
            expose: true
            type: string
            groups: [Default, Detailed, Autocomplete]
        calculationType:
            expose: true
            type: string
            groups: [Default, Detailed]
        position:
            expose: true
            type: integer
            groups: [Default, Detailed]
        translations:
            expose: true
            type: array
            groups: [Default, Detailed]
    virtual_properties:
        getName:
            serialized_name: name
            groups: [Default, Detailed, Autocomplete]
